spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: "/h2-console"
  r2dbc:
    url: "r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1"
    username: "sa"
    password:

server:
  port: 8443
  ssl:
    enabled: false

armeria:
  ports:
    - port: ${server.port}
      protocols: [ "http" ]